### ISSUE TITLE
ETIMEDOUT Error

### ISSUE THREAD

**Issue by MaxAndolini** [Maaaartin/adb-ts#1]
We have been using it for a long time, but now it constantly crashes and hangs in new adb versions.

Error:

connect ETIMEDOUT 127.0.0.1:5037

**Comment by MaxAndolini** [comment]
Windows 10 and latest adb

**Comment by Maaaartin** [comment]
I have tried to run `listDevices` against the newest adb version, which should be `33.0.1-8253317`, but had no issues. Is it a specific command which does not work on the new adb version? Can you also double check what adb version you are exactly using?

**Comment by MaxAndolini** [comment]
I started using it by sending commands through adb itself. That's why I don't use it anymore.
