### ISSUE TITLE
Can't call Client.exec with multiple parameters like "forward --list"

### ISSUE THREAD

**Issue by jwlilly** [Maaaartin/adb-ts#13]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `adb-ts@6.0.0` for the project I'm working on.

The `Client.exec` and `Client.execDevice` commands work but only if you have a single command with no parameters. This modification just changes the command to an array so that an unlimited number of parameters can be included. For example, if you wanted to list the forwarded ports, you would run the command `adb forward --list`. This will list all of the forwarded ports and the corresponding device serials. Without using an array and doing something like `Client.exec('forward --list')`, it throws an error. 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/adb-ts/lib/client.d.ts b/node_modules/adb-ts/lib/client.d.ts
index 0c4b893..7652c1a 100644
--- a/node_modules/adb-ts/lib/client.d.ts
+++ b/node_modules/adb-ts/lib/client.d.ts
@@ -420,12 +420,12 @@ export declare class Client {
     /**
      * Executes a given command via adb console interface.
      */
-    exec(cmd: string): Promise<string>;
+    exec(cmd: string[]): Promise<string>;
     /**
      * Executes a given command on specific device via adb console interface.
      *  Analogous to `adb -s <serial> <command>`.
      */
-    execDevice(serial: string, cmd: string): Promise<string>;
+    execDevice(serial: string, cmd: string[]): Promise<string>;
     /**
      * Executes a given command on specific device shell via adb console interface.
      * Analogous to `adb -s <serial> shell <command>` .
diff --git a/node_modules/adb-ts/lib/client.js b/node_modules/adb-ts/lib/client.js
index 0112d61..ad95d42 100644
--- a/node_modules/adb-ts/lib/client.js
+++ b/node_modules/adb-ts/lib/client.js
@@ -679,14 +679,14 @@ class Client {
      * Executes a given command via adb console interface.
      */
     exec(cmd) {
-        return this.execInternal(cmd);
+        return this.execInternal(...cmd);
     }
     /**
      * Executes a given command on specific device via adb console interface.
      *  Analogous to `adb -s <serial> <command>`.
      */
     execDevice(serial, cmd) {
-        return this.execInternal(...['-s', serial, cmd]);
+        return this.execInternal(...['-s', serial, ...cmd]);
     }
     /**
      * Executes a given command on specific device shell via adb console interface.
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Maaaartin** [comment]
@jwlilly Hi, thank you. I found the problem, will fix soon.

**Comment by Maaaartin** [comment]
@jwlilly would you mind checking out https://github.com/Maaaartin/adb-ts/pull/14? Just check out the branch and run the project locally. Would be helpful if you can confirm that the changes fix the issue.
