### ISSUE TITLE
When I get the Android version, I get the time back

### ISSUE THREAD

**Issue by chengazhen** [Maaaartin/adb-ts#15]
in properties

key =
'ro.build.version.release'
value =
Tue Aug 01 2000 00:00:00 GMT+0800 (中国标准时间)

i use ` const androidVersion = this.properties.get('ro.build.version.release')` is work

**Comment by chengazhen** [comment]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `adb-ts@6.0.0` for the project I'm working on.



Here is the diff that solved my problem:

```diff
diff --git a/node_modules/adb-ts/lib/util/functions.js b/node_modules/adb-ts/lib/util/functions.js
index 5a3820a..c9257a5 100644
--- a/node_modules/adb-ts/lib/util/functions.js
+++ b/node_modules/adb-ts/lib/util/functions.js
@@ -26,10 +26,12 @@ const stringToType = (value) => {
         return parsed;
     }
     catch {
-        const date = new Date(value);
-        if (!isNaN(date.getMilliseconds())) {
-            return date;
+        // Try to parse as date using Date.parse() which is more reliable
+        const timestamp = Date.parse(value);
+        if (!isNaN(timestamp)) {
+            return new Date(timestamp);
         }
+        // Return original value if not undefined, otherwise return undefined
         return value || undefined;
     }
 };
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by chengazhen** [comment]
When will the next version be released

**Comment by Maaaartin** [comment]
Problem was unreliable Date parsing. As Date can be represented in many ways using primitive types, automatic Date parsing was removed in 6.2.0 https://github.com/Maaaartin/adb-ts/pull/16
